from django.urls import path

from . import views

app_name = "academy"

urlpatterns = [
    path("", views.home, name="home"),
    path("analytics/", views.analytics_overview, name="analytics_overview"),
    path("psychologist/<int:psychologist_id>/", views.psychologist_dashboard, name="psychologist_dashboard"),
    path("course/<int:course_id>/", views.course_detail, name="course_detail"),
    path("lesson/<int:lesson_id>/", views.lesson_detail, name="lesson_detail"),
    path("test/<int:content_id>/submit/", views.submit_test, name="submit_test"),
    path("game/<int:content_id>/submit/", views.submit_game, name="submit_game"),
    path("psych/login/", views.psych_login, name="psych_login"),
    path("psych/logout/", views.psych_logout, name="psych_logout"),
    path("psych/", views.psych_dashboard, name="psych_dashboard"),
    path("psych/courses/new/", views.psych_course_create, name="psych_course_create"),
    path("psych/courses/<int:course_id>/", views.psych_course_edit, name="psych_course_edit"),
    path("psych/courses/<int:course_id>/delete/", views.psych_course_delete, name="psych_course_delete"),
    path("psych/lessons/new/", views.psych_lesson_create, name="psych_lesson_create"),
    path("psych/lessons/<int:lesson_id>/", views.psych_lesson_edit, name="psych_lesson_edit"),
    path("psych/lessons/<int:lesson_id>/delete/", views.psych_lesson_delete, name="psych_lesson_delete"),
    path("psych/contents/new/", views.psych_content_create, name="psych_content_create"),
    path("psych/contents/<int:content_id>/", views.psych_content_edit, name="psych_content_edit"),
    path("psych/contents/<int:content_id>/delete/", views.psych_content_delete, name="psych_content_delete"),
    path("psych/contents/<int:content_id>/remove-video-file/", views.psych_content_remove_video_file, name="psych_content_remove_video_file"),
    path("psych/contents/<int:content_id>/remove-video-preview/", views.psych_content_remove_video_preview, name="psych_content_remove_video_preview"),
    path("psych/games/<int:content_id>/editor/", views.psych_game_editor, name="psych_game_editor"),
    path("psych/games/<int:content_id>/scenes/save/", views.psych_game_scene_save, name="psych_game_scene_save"),
    path("psych/games/scenes/<int:scene_id>/delete/", views.psych_game_scene_delete, name="psych_game_scene_delete"),
    path("psych/games/<int:content_id>/avatars/builder/", views.psych_avatar_builder, name="psych_avatar_builder"),
    path("psych/games/<int:content_id>/avatars/create/", views.psych_avatar_create, name="psych_avatar_create"),
    path("psych/tests/<int:content_id>/", views.psych_test_editor, name="psych_test_editor"),
    path("psych/tests/<int:content_id>/questions/new/", views.psych_test_question_create, name="psych_test_question_create"),
    path("psych/tests/questions/<int:question_id>/edit/", views.psych_test_question_edit, name="psych_test_question_edit"),
    path("psych/tests/questions/<int:question_id>/remove-image/", views.psych_test_question_remove_image, name="psych_test_question_remove_image"),
    path("psych/tests/questions/<int:question_id>/delete/", views.psych_test_question_delete, name="psych_test_question_delete"),
    path("psych/tests/questions/<int:question_id>/options/new/", views.psych_test_option_create, name="psych_test_option_create"),
    path("psych/tests/options/<int:option_id>/edit/", views.psych_test_option_edit, name="psych_test_option_edit"),
    path("psych/tests/options/<int:option_id>/delete/", views.psych_test_option_delete, name="psych_test_option_delete"),
    path("psych/results/<int:result_id>/delete/", views.psych_result_delete, name="psych_result_delete"),
    path("psych/lessons/<int:lesson_id>/results/delete-all/", views.psych_lesson_results_delete_all, name="psych_lesson_results_delete_all"),
    path("psych/lessons/<int:lesson_id>/contents/reorder/", views.psych_contents_reorder, name="psych_contents_reorder"),
]
