# Generated by Django 6.0.3 on 2026-03-26 16:17

import academy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_psychologist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='private_access_token',
            field=models.CharField(default=academy.models.generate_private_access_token, editable=False, max_length=32),
        ),
    ]
