# Generated by Django 6.0.3 on 2026-03-26 16:21

import academy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_course_private_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='private_access_token',
            field=models.CharField(default=academy.models.generate_private_access_token, editable=False, max_length=32),
        ),
    ]
