# Generated by Django 6.0.3 on 2026-03-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_lesson_is_private_lesson_private_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_videos/'),
        ),
        migrations.AddField(
            model_name='lessoncontent',
            name='video_preview',
            field=models.FileField(blank=True, null=True, upload_to='lesson_video_previews/'),
        ),
    ]
