# Generated by Django 6.0.3 on 2026-03-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_lessoncontent_video_file_lessoncontent_video_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='testoption',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
