# Generated by Django 6.0.3 on 2026-03-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_testoption_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcontentresult',
            name='selected_answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
