# Generated by Django 6.0.3 on 2026-03-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_childcontentresult_selected_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='test_questions/'),
        ),
    ]
