# Generated by Django 6.0.3 on 2026-03-26 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_testquestion_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarPartAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('part_type', models.CharField(choices=[('body', 'Тело'), ('eyes', 'Глаза'), ('hair', 'Волосы'), ('clothes', 'Одежда'), ('accessory', 'Аксессуар')], max_length=20)),
                ('image', models.ImageField(upload_to='game/avatar_parts/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='game/backgrounds/')),
            ],
        ),
        migrations.CreateModel(
            name='GameScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=1)),
                ('width', models.PositiveIntegerField(default=960)),
                ('height', models.PositiveIntegerField(default=540)),
                ('question_text', models.TextField(blank=True)),
                ('answer_mode', models.CharField(choices=[('open', 'Открытый ответ'), ('choices', 'Выбор варианта')], default='open', max_length=20)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenes', to='academy.backgroundasset')),
                ('content', models.ForeignKey(limit_choices_to={'content_type': 'game'}, on_delete=django.db.models.deletion.CASCADE, related_name='game_scenes', to='academy.lessoncontent')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=1)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='academy.gamescene')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GameTextElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('x', models.FloatField(default=100)),
                ('y', models.FloatField(default=100)),
                ('width', models.FloatField(default=220)),
                ('font_size', models.PositiveIntegerField(default=18)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='academy.gamescene')),
            ],
        ),
        migrations.CreateModel(
            name='SavedAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory_part', models.ForeignKey(blank=True, limit_choices_to={'part_type': 'accessory'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_accessory_uses', to='academy.avatarpartasset')),
                ('body_part', models.ForeignKey(blank=True, limit_choices_to={'part_type': 'body'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_body_uses', to='academy.avatarpartasset')),
                ('clothes_part', models.ForeignKey(blank=True, limit_choices_to={'part_type': 'clothes'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_clothes_uses', to='academy.avatarpartasset')),
                ('eyes_part', models.ForeignKey(blank=True, limit_choices_to={'part_type': 'eyes'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_eyes_uses', to='academy.avatarpartasset')),
                ('hair_part', models.ForeignKey(blank=True, limit_choices_to={'part_type': 'hair'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_hair_uses', to='academy.avatarpartasset')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_avatars', to='academy.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='GameSceneObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(choices=[('character', 'Персонаж'), ('text', 'Текст')], default='character', max_length=20)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('x', models.FloatField(default=120)),
                ('y', models.FloatField(default=120)),
                ('width', models.FloatField(default=180)),
                ('height', models.FloatField(default=180)),
                ('scale', models.FloatField(default=1.0)),
                ('flip_x', models.BooleanField(default=False)),
                ('z_index', models.IntegerField(default=1)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scene_objects', to='academy.gamescene')),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_objects', to='academy.savedavatar')),
            ],
        ),
    ]
