# Generated by Django 6.0.3 on 2026-04-16 19:42

import academy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0009_avatarpartasset_backgroundasset_gamescene_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testoption',
            name='identifier',
            field=models.CharField(default=academy.models.generate_test_identifier, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='testoption',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testoption',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='answers_view',
            field=models.CharField(choices=[('tile', 'Плитка'), ('row', 'В один ряд'), ('stars', 'Звезды')], default='tile', max_length=20),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='help_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='identifier',
            field=models.CharField(default=academy.models.generate_test_identifier, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='shuffle_options',
            field=models.BooleanField(default=False),
        ),
    ]
