# Generated by Django 6.0.3 on 2026-06-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0015_homeslide_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncontent',
            name='video_preview',
            field=models.ImageField(blank=True, null=True, upload_to='lesson_video_previews/', verbose_name='Превью видео'),
        ),
    ]
