# Generated by Django 6.0.3 on 2026-06-19 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0016_alter_lessoncontent_video_preview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('viber', 'Viber'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('email', 'Email'), ('website', 'Сайт'), ('vk', 'VKontakte'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('twitter', 'Twitter / X'), ('odnoklassniki', 'Одноклассники'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('discord', 'Discord'), ('twitch', 'Twitch'), ('reddit', 'Reddit'), ('tumblr', 'Tumblr'), ('skype', 'Skype'), ('zoom', 'Zoom'), ('phone', 'Телефон')], max_length=50, verbose_name='Платформа')),
                ('url', models.URLField(help_text='Введите полный URL, включая https://', max_length=500, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, help_text='Отображать эту ссылку на сайте', verbose_name='Активно')),
                ('icon', models.ImageField(blank=True, help_text='Загрузите свою иконку для этой платформы (опционально)', null=True, upload_to='social_icons/', verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='academy.psychologist', verbose_name='Психолог')),
            ],
            options={
                'verbose_name': 'Социальная ссылка',
                'verbose_name_plural': 'Социальные ссылки',
                'ordering': ['order', 'platform'],
                'unique_together': {('psychologist', 'platform')},
            },
        ),
    ]
