# Generated by Django 6.0.3 on 2026-06-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0017_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Введите номер телефона в формате +79001234567', max_length=20, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('max', 'MAX'), ('vk', 'ВКонтакте'), ('phone', 'Телефон')], max_length=50, verbose_name='Платформа'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(blank=True, help_text='Введите полный URL, включая https:// (для телефона используйте tel:+79001234567)', max_length=500, null=True, verbose_name='Ссылка'),
        ),
    ]
